### ISSUE TITLE
Suggestion: Setting to disable features?

### ISSUE THREAD

**Issue by jruaaa** [Pauloo27/homepage#2]
EG I only use GCal, remove trello and the todo list. Could you make it possible to disable other features, maybe in the general settings as a toggle that removes all the cards? You could either make the cards adaptive, or shift the bookmark bar down into a bookmark card and stretch the searchbar all over the top, idk.

**Comment by Pauloo27** [comment]
That's a nice idea, but how should the page looks when you have only 2 middle cars enabled (lets say trello and To Do), should they be 50%/%50? And what about when you have only one, should it take 100% width or be centered with white space around?

![image](https://user-images.githubusercontent.com/23013073/88857068-fa87ee00-d1cb-11ea-96b4-fed8529ca9bc.png)

![image](https://user-images.githubusercontent.com/23013073/88857112-0ecbeb00-d1cc-11ea-9234-b0e09c2c7765.png)

![image](https://user-images.githubusercontent.com/23013073/88857263-55b9e080-d1cc-11ea-81e4-1a7125e09f3c.png)

**Comment by jruaaa** [comment]
2 cards = 50/50, 1 card  = bookmarks tab becomes a card. basically there should always be two cards. another thing that you could add is an rss reader or email integration but I understand if its a bit difficult because i don't do frontend.

**Comment by Pauloo27** [comment]
Sorry about the delay.

The last few commits are related to this issue. The only thing that I haven't done is the "bookmarks as card". I'll improve the bookmark later.

The problem with e-mail is that this homepage doesn't have a "backend". Everything is done in the frontend using the JS Client API of the services. I don't think I can make a good and safe e-mail client there. The RSS feed is more simple but still a hard work to make it good. I will try something in the future.

Thank you for the suggestions! 

Can you take a look at https://pauloo27.github.io/homepage/ and give me some feedback about the "toggle" features?

**Comment by jruaaa** [comment]
That's basically it! The one thing is if you only have one card enabled, maybe shifting the bookmark toolbar down into a card, splitting it into a 50/50 with a remaining card would be a more efficient use of space. I'll demonstrate: 
![example](https://user-images.githubusercontent.com/32626650/89212022-9c665c80-d577-11ea-9303-e0b091ed2412.png)

**Comment by Pauloo27** [comment]
I tried to make the layout look like this but the chrome crashed before I could take a screenshot :(. Anyway, I think that the bookmarks as a card would look better if it was categorized. In the future I think I will fix the bookmark bar and make it as a card, but just a bunch of icons doesn't look good.

**Comment by jruaaa** [comment]
TBF it looks fine to me, as a student I have so many resources and classes I need to keep track of, and this would take care of most of it.

**Comment by Pauloo27** [comment]
@jruaaa 

I added a option "Expand bookmark" in the general settings. It only works with 2 or less enabled cards. Can you give me some feed back? 

Thanks in advance.
